=== dawmendoza2009/EXAMENFINAL/XSD/MetereologiaXSD.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="metereologia">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="comunidades" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="comunidaAutonoma"  minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="provincias" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="provincia"  minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="poblaciones" >
													<xs:complexType>
														<xs:sequence>
															<xs:element ref="poblacion" minOccurs="1" maxOccurs="unbounded"/>															 
														</xs:sequence>
													</xs:complexType>
													</xs:element>
												</xs:sequence>
												
										<!--definición de atributo Provincia-->
										<xs:attribute name="nombre" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>																							
										 
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<!--definición de atributo CCAA-->
						<xs:attribute name="nombre" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				
				</xs:sequence>
				</xs:complexType>
			</xs:element>
			</xs:sequence>

		</xs:complexType>
	</xs:element>


	<!-- Elemento población -->
<xs:element name="poblacion">
	<xs:complexType>
 	<xs:sequence>
	<xs:element name="fecha" type="xs:date"/>	
	<xs:element name="temperatura-maxima" type="xs:string"/>	
	<xs:element name="temperatura-minima" type="xs:string"/>
	<xs:element name="probabilidadlluvia" type="xs:string"/>
	<xs:element name="avisos" minOccurs="1" maxOccurs="10">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="aviso" type="enumeracion" minOccurs="1" maxOccurs="10"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>	 											 
	</xs:sequence>
	<!--definición de atributo CCAA-->
	<xs:attribute name="nombre" type="xs:string" use="required"/>
 </xs:complexType>
</xs:element>
	
 <!--RESTRINCIONES:-->	 
	<xs:simpleType name="enumeracion">
		<xs:restriction base="xs:string">
			<xs:pattern value="Viento|Nieve|Tormenta|Huracán"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dawmendoza2009/EXAMENFINAL/XSD/Metereologia.xml
<?xml version="1.0" encoding="UTF-8"?>
<metereologia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="MetereologiaXSD.xsd">
	<comunidades>
        <comunidaAutonoma nombre="Leon">
            <provincias>
                <provincia nombre="Madrids">
                    <poblaciones>
                        <poblacion nombre="Madrid">
                            <fecha>2022-12-05</fecha>
                            <temperatura-maxima>ww</temperatura-maxima>
                            <temperatura-minima>ww</temperatura-minima>
                            <probabilidadlluvia>ww</probabilidadlluvia>
                            <avisos>
                                <aviso>Viento</aviso>
                                <aviso>Tormenta</aviso>
                            </avisos>
                        </poblacion>
                    </poblaciones>       
                </provincia>
    
            </provincias>
        </comunidaAutonoma>
        
    </comunidades>
   
					
</metereologia>
